var hello = 5;
var hi = "5";
console.log(hello, hi);
var myBool = true;
console.log(myBool);
var numArr = [11, 23];
var strArr = ['11', "meow", '1m'];
var numArrTuple = ['12', 13, 14];
console.log(numArr, strArr, numArrTuple);
var myUnion;
myUnion = 46;
console.log(myUnion);
